batch_size: 128
seed: 42
lr: 0.01
num_workers: 8
num_classes: 10
image_size: 224 
num_epochs: 20
momentum: 0.9
train_dir: "data/Fast Food Classification V2/Train"
val_dir: "data/Fast Food Classification V2/Valid"
weight_decay: 0.0004
plot_dir: "plots"
model_save_dir: "saved_models"

